# Generated by Django 5.0.4 on 2024-04-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre_completo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
